services:
  nhdl:
    build: .
    container_name: nhdl
    restart: unless-stopped
    environment:
      - DOWNLOAD_DIR=/mnt/hdd-music/download/nhdl
      - TZ=Asia/Jakarta
      - WEB_GUI=true
    ports:
      - "8098:8080"
    volumes:
      - /mnt/hdd-media/nhdl/downloads:/downloads
      - /mnt/hdd-media:/mnt/hdd-media
      - /mnt/hdd-music:/mnt/hdd-music
